"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[cmd_duration]
disabled = true

[git_branch]
ignore_branches = ['master', 'main', 'production']

[directory]
truncate_to_repo = true
truncation_symbol = "~/../"

[package]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[php]
disabled = true

[python]
disabled = true

[golang]
disabled = true
