" basic
set nocompatible
filetype off
set showcmd
set history=1000

" visual
syntax on
set number
set cursorline
set nowrap

" color scheme
colorscheme delek
let theme = system('defaults read -g AppleInterfaceStyle')
if theme =~ 'Dark'
    colorscheme ron
endif

" spaces and tabs
set shiftwidth=4
set tabstop=4
set expandtab

" search
set incsearch
set ignorecase
set smartcase
set hlsearch
set showmatch

" autocomplete
set wildmenu
set wildmode=list:longest

" vundle
set rtp+=~/.config/vim/bundle/Vundle.vim
call vundle#begin('~/.config/vim/plugins')
Plugin 'VundleVim/Vundle.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
call vundle#end()
filetype plugin indent on

" shortcodes
nnoremap <leader>f :Files<CR>
nnoremap <leader>g :GFiles<CR>

