" basic
set nocompatible
set showcmd
set history=1000

" mouse and clipboard support
set mouse=a
set clipboard=unnamed
vnoremap <LeftRelease> y

" open fzf when no file path has been passed on
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | execute 'Files' | endif

" visual
syntax on
set number
set cursorline
set nowrap

" color scheme
colorscheme delek
let theme = system('defaults read -g AppleInterfaceStyle')
if theme =~ 'Dark'
    colorscheme ron
endif

" spaces and tabs
set shiftwidth=4
set tabstop=4
set expandtab

" search
set incsearch
set ignorecase
set smartcase
set hlsearch
set showmatch

" autocomplete
set wildmenu
set wildmode=list:longest

" plugins
set rtp+=~/.config/vim
call plug#begin('~/.config/vim/plugins')
Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()

" shortcodes
nnoremap <leader>f :Files<CR>
nnoremap <leader>g :GFiles<CR>

